---
- name: Configure default shell "{{ host.username }}"
  user:
    name: "{{ host.username }}"
    shell: /usr/bin/zsh
    state: present

- name: Download script oh-my-zsh
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/install.sh
    mode: 0777

- name: Check folder oh-my-zsh exists
  stat:
    path: /home/{{ host.username }}/.oh-my-zsh
  register: oh_my_zsh_exists

- name: Execute script install oh-my-zsh
  shell: /tmp/install.sh --unattended
  become: yes
  become_user: "{{ host.username }}"
  when: not oh_my_zsh_exists.stat.exists

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /home/{{ host.username }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  become: yes
  become_user: "{{ host.username }}"
  when: not oh_my_zsh_exists.stat.exists

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /home/{{ host.username }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  become: yes
  become_user: "{{ host.username }}"
  when: not oh_my_zsh_exists.stat.exists

- name: Create .zshrc
  ansible.builtin.template:
    src: zshrc.j2
    dest: /home/{{ host.username }}/.zshrc
    owner: "{{ host.username }}"
    group: "{{ host.username }}"
    mode: "0644"
