---
- name: Check vscode exists
  stat:
    path: /usr/bin/code
  register: vscode_already_exists

- name: Add microsoft Apt signing key
  ansible.builtin.apt_key:
    id: EB3E94ADBE1229CF
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/packages.microsoft.gpg
  when: not vscode_already_exists.stat.exists

- name: Copy repository vscode
  copy:
    src: vscode/vscode.list
    dest: /etc/apt/sources.list.d/vscode.list
  when: not vscode_already_exists.stat.exists

- name: Install dependencies vscode
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes
  when: not vscode_already_exists.stat.exists

- name: Install vscode
  apt:
    name: code
    state: present
  when: not vscode_already_exists.stat.exists